version: "3.8"
services:
  qiskit-jupyter:
    build: .
    # image: ghcr.io/flours/qiskit:1.0.0
    volumes:
      - ./mywork:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: qiskit-jupyter
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    environment:
      - JUPYTER_ENABLE_LAB=yes
