name: build and publish docker

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      image_name: qiskit
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}:1.0.0
